-- Zippy Logistics — Initial Supabase Schema Migration
-- Generated from DB SCHEMA.txt
-- Tables: 25 | Indexes: 80+ | FK relationships: full
-- Compatible with PostgreSQL 15+ / Supabase

-- ============================================================
-- ZIPPY LOGISTICS — COMPLETE DATABASE SCHEMA
-- PostgreSQL 15+ (Supabase compatible)
-- ============================================================
-- Conventions:
--   - UUID primary keys (generated by default)
--   - snake_case naming
--   - created_at / updated_at on every table
--   - CHECK constraints for enums
--   - Explicit FOREIGN KEY relationships
--   - Indexes on all FK columns + high-query columns
-- ============================================================

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "cube";        -- Required by earthdistance
CREATE EXTENSION IF NOT EXISTS "earthdistance";  -- Provides ll_to_earth()
CREATE EXTENSION IF NOT EXISTS "postgis";     -- For geospatial queries


-- ============================================================
-- 1. CITY & GEOGRAPHY
-- ============================================================

CREATE TABLE cities (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name            VARCHAR(100) NOT NULL,
    tier            VARCHAR(10) NOT NULL CHECK (tier IN ('metro', 'tier_1', 'tier_2', 'tier_3')),
    state           VARCHAR(100) NOT NULL,
    pincode         VARCHAR(6) NOT NULL,
    latitude        DECIMAL(10, 7),
    longitude       DECIMAL(10, 7),
    is_hill_station BOOLEAN DEFAULT FALSE,
    is_remote       BOOLEAN DEFAULT FALSE,
    is_industrial_cluster BOOLEAN DEFAULT FALSE,
    nearby_highway  VARCHAR(50),           -- e.g., 'NH44', 'SH17'
    altitude_m      DECIMAL(8, 2),
    climate_risk    VARCHAR(50),           -- e.g., 'monsoon_flood', 'extreme_heat'
    created_at      TIMESTAMP DEFAULT NOW(),
    updated_at      TIMESTAMP DEFAULT NOW(),
    UNIQUE(name, state)
);

CREATE INDEX idx_cities_tier ON cities(tier);
CREATE INDEX idx_cities_state ON cities(state);
CREATE INDEX idx_cities_pincode ON cities(pincode);
CREATE INDEX idx_cities_location ON cities USING GIST (
    ll_to_earth(latitude, longitude)
);


-- ============================================================
-- 2. USER & AUTHENTICATION
-- ============================================================

CREATE TABLE users (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    email           VARCHAR(255) UNIQUE,
    phone           VARCHAR(15) NOT NULL UNIQUE,  -- +91XXXXXXXXXX
    full_name       VARCHAR(200) NOT NULL,
    role            VARCHAR(20) NOT NULL CHECK (role IN ('vendor', 'customer', 'admin', 'driver')),
    is_active       BOOLEAN DEFAULT TRUE,
    is_verified     BOOLEAN DEFAULT FALSE,
    blocked         BOOLEAN DEFAULT FALSE,
    block_reason    TEXT,
    created_at      TIMESTAMP DEFAULT NOW(),
    updated_at      TIMESTAMP DEFAULT NOW(),
    last_login_at   TIMESTAMP
);

CREATE INDEX idx_users_role ON users(role);
CREATE INDEX idx_users_phone ON users(phone);
CREATE INDEX idx_users_active ON users(is_active) WHERE is_active = TRUE;


-- ============================================================
-- 3. CUSTOMERS (Warehouses, Manufacturers, Distributors)
-- ============================================================

CREATE TABLE customers (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id             UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    company_name        VARCHAR(255),
    gst_number          VARCHAR(15),
    customer_type       VARCHAR(30) NOT NULL CHECK (customer_type IN ('warehouse', 'manufacturer', 'distributor', 'individual')),
    segment             VARCHAR(20) NOT NULL DEFAULT 'individual' CHECK (segment IN ('individual', 'sme', 'enterprise')),
    default_pincode     VARCHAR(6) NOT NULL,
    city_id             UUID REFERENCES cities(id),
    credit_limit        DECIMAL(14, 2) DEFAULT 0,
    payment_terms_type  VARCHAR(30) DEFAULT 'advance' CHECK (payment_terms_type IN ('advance', 'bill_to_bill', 'credit_30', 'credit_60', 'monthly')),
    is_contracted       BOOLEAN DEFAULT FALSE,
    contract_start_date DATE,
    contract_end_date   DATE,
    created_at          TIMESTAMP DEFAULT NOW(),
    updated_at          TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_customers_user_id ON customers(user_id);
CREATE INDEX idx_customers_city_id ON customers(city_id);
CREATE INDEX idx_customers_segment ON customers(segment);
CREATE INDEX idx_customers_contracted ON customers(is_contracted) WHERE is_contracted = TRUE;


-- ============================================================
-- 4. VENDORS (Vehicle Owners, Transport Companies)
-- ============================================================

CREATE TABLE vendors (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id             UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    company_name        VARCHAR(255),
    vendor_type         VARCHAR(30) NOT NULL CHECK (vendor_type IN ('independent_owner', 'transport_company', 'fleet_operator')),
    gst_number          VARCHAR(15),
    is_contracted       BOOLEAN DEFAULT FALSE,
    contract_start_date DATE,
    contract_end_date   DATE,
    contract_day        INTEGER CHECK (contract_day BETWEEN 1 AND 28),  -- e.g., 5th of month
    total_vehicles      INTEGER DEFAULT 0,
    default_city_id     UUID REFERENCES cities(id),
    created_at          TIMESTAMP DEFAULT NOW(),
    updated_at          TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_vendors_user_id ON vendors(user_id);
CREATE INDEX idx_vendors_city_id ON vendors(default_city_id);
CREATE INDEX idx_vendors_contracted ON vendors(is_contracted) WHERE is_contracted = TRUE;


-- ============================================================
-- 5. DRIVERS
-- ============================================================

CREATE TABLE drivers (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id             UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    vendor_id           UUID REFERENCES vendors(id) ON DELETE SET NULL,
    license_number      VARCHAR(30) NOT NULL UNIQUE,
    license_expiry      DATE NOT NULL,
    ownership_type      VARCHAR(30) NOT NULL CHECK (ownership_type IN ('owner_driver', 'salaried_driver')),
    is_active           BOOLEAN DEFAULT TRUE,
    current_status      VARCHAR(20) DEFAULT 'offline' CHECK (current_status IN ('online', 'offline', 'in_shipment', 'on_leave')),
    current_city_id     UUID REFERENCES cities(id),
    current_latitude    DECIMAL(10, 7),
    current_longitude   DECIMAL(10, 7),
    last_location_at    TIMESTAMP,
    created_at          TIMESTAMP DEFAULT NOW(),
    updated_at          TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_drivers_user_id ON drivers(user_id);
CREATE INDEX idx_drivers_vendor_id ON drivers(vendor_id);
CREATE INDEX idx_drivers_status ON drivers(current_status);
CREATE INDEX idx_drivers_city ON drivers(current_city_id);


-- ============================================================
-- 6. VEHICLE MODELS & FLEET
-- ============================================================

CREATE TABLE vehicle_models (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    brand               VARCHAR(50) NOT NULL,  -- Tata, Ashok Leyland, Mahindra, Eicher, Volvo, Bharat Benz
    model_name          VARCHAR(100) NOT NULL,
    vehicle_class       VARCHAR(10) NOT NULL CHECK (vehicle_class IN ('LCV', 'MCV', 'HCV')),
    body_type           VARCHAR(20) NOT NULL CHECK (body_type IN ('open', 'closed', 'flatbed', 'freezer', 'container', 'tanker')),
    tonnage_capacity    DECIMAL(6, 2) NOT NULL,  -- in tons
    length_ft           DECIMAL(5, 2),
    width_ft            DECIMAL(5, 2),
    height_ft           DECIMAL(5, 2),
    max_volume_cbm      DECIMAL(8, 2),
    fuel_type           VARCHAR(20) CHECK (fuel_type IN ('diesel', 'cng', 'electric', 'petrol')),
    mileage_kmpl        DECIMAL(5, 2),
    axles               INTEGER,
    is_national_permit  BOOLEAN DEFAULT FALSE,
    created_at          TIMESTAMP DEFAULT NOW(),
    UNIQUE(brand, model_name, body_type)
);

CREATE INDEX idx_vehicle_models_class ON vehicle_models(vehicle_class);
CREATE INDEX idx_vehicle_models_body ON vehicle_models(body_type);
CREATE INDEX idx_vehicle_models_tonnage ON vehicle_models(tonnage_capacity);

-- Actual vehicles in the fleet
CREATE TABLE vehicles (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    vendor_id           UUID NOT NULL REFERENCES vendors(id) ON DELETE CASCADE,
    driver_id           UUID REFERENCES drivers(id) ON DELETE SET NULL,
    model_id            UUID NOT NULL REFERENCES vehicle_models(id),
    registration_number VARCHAR(20) NOT NULL UNIQUE,
    vehicle_age_years   INTEGER,
    insurance_valid_until DATE,
    fitness_cert_until  DATE,
    emission_cert_until DATE,
    carbon_cert_valid   BOOLEAN DEFAULT FALSE,
    is_national_permit  BOOLEAN DEFAULT FALSE,
    current_status      VARCHAR(20) DEFAULT 'idle' CHECK (current_status IN ('idle', 'in_shipment', 'maintenance', 'blocked')),
    current_city_id     UUID REFERENCES cities(id),
    current_latitude    DECIMAL(10, 7),
    current_longitude   DECIMAL(10, 7),
    last_location_at    TIMESTAMP,
    is_online           BOOLEAN DEFAULT FALSE,
    created_at          TIMESTAMP DEFAULT NOW(),
    updated_at          TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_vehicles_vendor ON vehicles(vendor_id);
CREATE INDEX idx_vehicles_driver ON vehicles(driver_id);
CREATE INDEX idx_vehicles_model ON vehicles(model_id);
CREATE INDEX idx_vehicles_status ON vehicles(current_status);
CREATE INDEX idx_vehicles_online ON vehicles(is_online) WHERE is_online = TRUE;
CREATE INDEX idx_vehicles_city ON vehicles(current_city_id);


-- ============================================================
-- 7. MATERIAL TYPES
-- ============================================================

CREATE TABLE material_types (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name            VARCHAR(100) NOT NULL UNIQUE,  -- Commodity, Electronics, Heavy Engineering, Pharma, etc.
    required_body   VARCHAR(20) NOT NULL CHECK (required_body IN ('open', 'closed', 'flatbed', 'freezer', 'container', 'tanker')),
    is_hazardous    BOOLEAN DEFAULT FALSE,
    is_banned       BOOLEAN DEFAULT FALSE,
    max_weight_tons DECIMAL(6, 2),
    description     TEXT,
    created_at      TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_material_types_body ON material_types(required_body);


-- ============================================================
-- 8. ORDERS (Core State Machine)
-- ============================================================

CREATE TABLE orders (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    order_number        VARCHAR(20) NOT NULL UNIQUE,  -- e.g., ZIP-2026-000001
    customer_id         UUID NOT NULL REFERENCES customers(id),
    
    -- Route
    origin_city_id      UUID NOT NULL REFERENCES cities(id),
    destination_city_id UUID NOT NULL REFERENCES cities(id),
    origin_pincode      VARCHAR(6) NOT NULL,
    destination_pincode VARCHAR(6) NOT NULL,
    
    -- Cargo
    material_type_id    UUID NOT NULL REFERENCES material_types(id),
    cargo_weight_tons   DECIMAL(6, 2) NOT NULL,
    cargo_volume_cbm    DECIMAL(8, 2),
    declared_value      DECIMAL(14, 2) NOT NULL DEFAULT 0,
    
    -- Service
    service_tier        VARCHAR(20) NOT NULL DEFAULT 'standard' CHECK (service_tier IN ('standard', 'express', 'premium')),
    delivery_type       VARCHAR(20) NOT NULL DEFAULT 'normal' CHECK (delivery_type IN ('normal', 'express')),
    load_type           VARCHAR(20) NOT NULL DEFAULT 'full_load' CHECK (load_type IN ('full_load', 'part_load', 'multi_spot')),
    
    -- Assignment
    assigned_vehicle_id UUID REFERENCES vehicles(id),
    assigned_driver_id  UUID REFERENCES drivers(id),
    
    -- State Machine
    status              VARCHAR(20) NOT NULL DEFAULT 'draft' CHECK (status IN (
                            'draft', 'payment_pending', 'confirmed', 'vehicle_search',
                            'driver_assigned', 'enroute', 'delivered', 'settlement', 'closed', 'cancelled'
                        )),
    payment_status      VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (payment_status IN (
                            'pending', 'advance_paid', 'partially_paid', 'fully_paid', 'refunded', 'credit', 'on_hold'
                        )),
    
    -- Scheduling
    scheduled_pickup_at TIMESTAMP,
    scheduled_delivery_at TIMESTAMP,
    actual_pickup_at    TIMESTAMP,
    actual_delivery_at    TIMESTAMP,
    
    -- Flags
    is_interstate       BOOLEAN DEFAULT FALSE,
    is_local            BOOLEAN DEFAULT FALSE,
    is_prebooking       BOOLEAN DEFAULT FALSE,
    is_tobilled_to_consignee BOOLEAN DEFAULT FALSE,  -- To-pay order
    
    -- Consignee (if different from customer)
    consignee_name      VARCHAR(200),
    consignee_phone     VARCHAR(15),
    consignee_address   TEXT,
    
    -- Pricing (locked at confirmation)
    quoted_price        DECIMAL(14, 2),
    final_price         DECIMAL(14, 2),
    discount_percent    DECIMAL(5, 2) DEFAULT 0,
    
    -- Meta
    cancellation_reason TEXT,
    cancelled_by        VARCHAR(20),
    created_at          TIMESTAMP DEFAULT NOW(),
    updated_at          TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_orders_customer ON orders(customer_id);
CREATE INDEX idx_orders_origin ON orders(origin_city_id);
CREATE INDEX idx_orders_destination ON orders(destination_city_id);
CREATE INDEX idx_orders_status ON orders(status);
CREATE INDEX idx_orders_payment_status ON orders(payment_status);
CREATE INDEX idx_orders_vehicle ON orders(assigned_vehicle_id);
CREATE INDEX idx_orders_driver ON orders(assigned_driver_id);
CREATE INDEX idx_orders_created ON orders(created_at DESC);
CREATE INDEX idx_orders_scheduled ON orders(scheduled_pickup_at);
CREATE INDEX idx_orders_interstate ON orders(is_interstate);

-- Order state transition history (audit trail for state machine)
CREATE TABLE order_state_history (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    order_id        UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    from_status     VARCHAR(20),
    to_status       VARCHAR(20) NOT NULL,
    changed_by_type VARCHAR(20) NOT NULL CHECK (changed_by_type IN ('system', 'admin', 'customer', 'driver', 'api')),
    changed_by_id   UUID,
    reason          TEXT,
    metadata        JSONB,  -- extra context
    created_at      TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_order_history_order ON order_state_history(order_id);
CREATE INDEX idx_order_history_created ON order_state_history(created_at DESC);


-- ============================================================
-- 9. INVOICE & POD
-- ============================================================

CREATE TABLE invoices (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    order_id        UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    invoice_number  VARCHAR(30) NOT NULL UNIQUE,
    amount          DECIMAL(14, 2) NOT NULL,
    gst_amount      DECIMAL(14, 2) DEFAULT 0,
    total_amount    DECIMAL(14, 2) NOT NULL,
    issued_at       TIMESTAMP DEFAULT NOW(),
    due_date        DATE,
    status          VARCHAR(20) DEFAULT 'issued' CHECK (status IN ('issued', 'paid', 'overdue', 'cancelled')),
    file_url        TEXT,  -- S3/Cloudflare R2 URL
    uploaded_by     UUID REFERENCES users(id),
    created_at      TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_invoices_order ON invoices(order_id);
CREATE INDEX idx_invoices_status ON invoices(status);
CREATE INDEX idx_invoices_due ON invoices(due_date);

CREATE TABLE pod_documents (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    order_id        UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    pod_number      VARCHAR(30),
    received_at     TIMESTAMP DEFAULT NOW(),
    received_by     VARCHAR(20) CHECK (received_by IN ('driver', 'consignee', 'admin')),
    condition       VARCHAR(20) DEFAULT 'good' CHECK (condition IN ('good', 'damaged', 'partial', 'missing')),
    notes           TEXT,
    file_url        TEXT NOT NULL,  -- scanned POD image
    uploaded_by     UUID REFERENCES users(id),
    created_at      TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_pod_order ON pod_documents(order_id);
CREATE INDEX idx_pod_received ON pod_documents(received_at DESC);


-- ============================================================
-- 10. PAYMENT SYSTEM
-- ============================================================

-- Payment terms configuration
CREATE TABLE payment_terms (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    party_type      VARCHAR(10) NOT NULL CHECK (party_type IN ('customer', 'vendor')),
    party_id        UUID NOT NULL,  -- references customers.id or vendors.id
    term_type       VARCHAR(30) NOT NULL CHECK (term_type IN (
                        'advance_60', 'advance_80', 'full_advance',
                        'bill_to_bill', 'credit_30', 'credit_60', 'monthly_cycle',
                        'to_pay', 'contract_monthly'
                    )),
    advance_percent DECIMAL(5, 2),  -- e.g., 60.00 for 60%
    is_active       BOOLEAN DEFAULT TRUE,
    created_at      TIMESTAMP DEFAULT NOW(),
    updated_at      TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_payment_terms_party ON payment_terms(party_type, party_id);

-- Actual payment transactions
CREATE TABLE payments (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    order_id            UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    party_type          VARCHAR(10) NOT NULL CHECK (party_type IN ('customer', 'vendor')),
    party_id            UUID NOT NULL,  -- customers.id or vendors.id
    payment_type        VARCHAR(20) NOT NULL CHECK (payment_type IN ('advance', 'balance', 'full', 'refund', 'settlement', 'penalty')),
    amount              DECIMAL(14, 2) NOT NULL,
    currency            VARCHAR(3) DEFAULT 'INR',
    status              VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN (
                            'pending', 'processing', 'completed', 'failed', 'held', 'refunded'
                        )),
    gateway_ref         VARCHAR(100),  -- Razorpay payment ID
    gateway_status      VARCHAR(50),
    paid_at             TIMESTAMP,
    due_date            DATE,
    notes               TEXT,
    created_at          TIMESTAMP DEFAULT NOW(),
    updated_at          TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_payments_order ON payments(order_id);
CREATE INDEX idx_payments_party ON payments(party_type, party_id);
CREATE INDEX idx_payments_status ON payments(status);
CREATE INDEX idx_payments_type ON payments(payment_type);
CREATE INDEX idx_payments_due ON payments(due_date);
CREATE INDEX idx_payments_gateway ON payments(gateway_ref);

-- Payment holds (disputes, missing POD, theft investigation)
CREATE TABLE payment_holds (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    payment_id      UUID NOT NULL REFERENCES payments(id) ON DELETE CASCADE,
    hold_reason     VARCHAR(50) NOT NULL CHECK (hold_reason IN (
                        'missing_pod', 'theft_investigation', 'damage_claim',
                        'dispute', 'admin_review', 'legal_issue'
                    )),
    held_amount     DECIMAL(14, 2) NOT NULL,
    held_by         UUID REFERENCES users(id),
    held_at         TIMESTAMP DEFAULT NOW(),
    released_at     TIMESTAMP,
    release_reason  TEXT,
    released_by     UUID REFERENCES users(id)
);

CREATE INDEX idx_holds_payment ON payment_holds(payment_id);
CREATE INDEX idx_holds_active ON payment_holds(payment_id) WHERE released_at IS NULL;

-- Refunds
CREATE TABLE refunds (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    payment_id      UUID NOT NULL REFERENCES payments(id) ON DELETE CASCADE,
    order_id        UUID NOT NULL REFERENCES orders(id),
    refund_amount   DECIMAL(14, 2) NOT NULL,
    reason          VARCHAR(50) NOT NULL CHECK (reason IN (
                        'order_cancelled_30min', 'vehicle_removed', 'accident',
                        'flat_tyre', 'shipment_failure', 'theft', 'missing_goods',
                        'excess_payment', 'double_payment', 'miscalculation', 'penalty_deduction'
                    )),
    requires_admin_approval BOOLEAN DEFAULT FALSE,
    approved_by     UUID REFERENCES users(id),
    approved_at     TIMESTAMP,
    status          VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'processed', 'rejected')),
    gateway_refund_ref VARCHAR(100),
    processed_at    TIMESTAMP,
    notes           TEXT,
    created_at      TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_refunds_payment ON refunds(payment_id);
CREATE INDEX idx_refunds_order ON refunds(order_id);
CREATE INDEX idx_refunds_status ON refunds(status);


-- ============================================================
-- 11. PRICING ENGINE
-- ============================================================

CREATE TABLE pricing_base_rates (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    vehicle_class       VARCHAR(10) NOT NULL CHECK (vehicle_class IN ('LCV', 'MCV', 'HCV', 'mini_truck', 'trailer')),
    origin_tier         VARCHAR(10) NOT NULL,
    destination_tier    VARCHAR(10) NOT NULL,
    base_rate_per_km    DECIMAL(8, 2) NOT NULL,
    min_charge          DECIMAL(10, 2) NOT NULL DEFAULT 500,
    driver_cost_fixed   DECIMAL(10, 2) DEFAULT 1500,
    maintenance_per_km  DECIMAL(6, 2) DEFAULT 2.5,
    toll_per_km         DECIMAL(6, 2) DEFAULT 1.2,
    fuel_price_per_l    DECIMAL(6, 2) DEFAULT 91.0,
    mileage_kmpl        DECIMAL(5, 2) DEFAULT 6.0,
    effective_from      DATE NOT NULL DEFAULT CURRENT_DATE,
    effective_until     DATE,
    created_at          TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_pricing_route ON pricing_base_rates(vehicle_class, origin_tier, destination_tier);
CREATE INDEX idx_pricing_dates ON pricing_base_rates(effective_from, effective_until);

-- Dynamic pricing factors (multipliers)
CREATE TABLE pricing_factors (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    factor_type     VARCHAR(40) NOT NULL CHECK (factor_type IN (
                        'hill_station', 'remote_area', 'peak_season', 'weather_surge',
                        'metro_congestion', 'interstate_permit', 'return_trip_bonus',
                        'no_return_trip', 'express_multiplier', 'premium_multiplier'
                    )),
    factor_value    DECIMAL(5, 3) NOT NULL,  -- e.g., 1.150 for 15% increase
    description     TEXT,
    is_active       BOOLEAN DEFAULT TRUE,
    created_at      TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_pricing_factors_type ON pricing_factors(factor_type) WHERE is_active = TRUE;

-- Route distance cache (for fast pricing lookups)
CREATE TABLE route_distances (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    origin_city_id  UUID NOT NULL REFERENCES cities(id),
    dest_city_id    UUID NOT NULL REFERENCES cities(id),
    distance_km     DECIMAL(8, 2) NOT NULL,
    duration_min    INTEGER,
    source          VARCHAR(20) DEFAULT 'mapmyindia' CHECK (source IN ('mapmyindia', 'mapbox', 'manual', 'osrm')),
    has_return_trip BOOLEAN DEFAULT FALSE,  -- pair trading city
    last_updated    TIMESTAMP DEFAULT NOW(),
    UNIQUE(origin_city_id, dest_city_id)
);

CREATE INDEX idx_route_distances_pair ON route_distances(origin_city_id, dest_city_id);


-- ============================================================
-- 12. SCORING SYSTEMS
-- ============================================================

-- Daily driver metrics (aggregated per day)
CREATE TABLE driver_metrics (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    driver_id           UUID NOT NULL REFERENCES drivers(id) ON DELETE CASCADE,
    metric_date         DATE NOT NULL,
    total_orders        INTEGER DEFAULT 0,
    accepted_orders     INTEGER DEFAULT 0,
    completed_orders    INTEGER DEFAULT 0,
    cancelled_orders    INTEGER DEFAULT 0,
    ignored_orders      INTEGER DEFAULT 0,
    on_time_deliveries  INTEGER DEFAULT 0,
    delayed_deliveries  INTEGER DEFAULT 0,
    pod_uploaded_count  INTEGER DEFAULT 0,
    invoice_uploaded    INTEGER DEFAULT 0,
    customer_complaints INTEGER DEFAULT 0,
    theft_incidents     INTEGER DEFAULT 0,
    shortage_incidents  INTEGER DEFAULT 0,
    misbehavior_count   INTEGER DEFAULT 0,
    response_time_avg   DECIMAL(6, 2),  -- minutes to respond
    calculated_score    DECIMAL(5, 2),
    created_at          TIMESTAMP DEFAULT NOW(),
    UNIQUE(driver_id, metric_date)
);

CREATE INDEX idx_driver_metrics_driver ON driver_metrics(driver_id);
CREATE INDEX idx_driver_metrics_date ON driver_metrics(metric_date DESC);

-- Daily customer metrics
CREATE TABLE customer_metrics (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    customer_id         UUID NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    metric_date         DATE NOT NULL,
    total_orders        INTEGER DEFAULT 0,
    cancelled_orders    INTEGER DEFAULT 0,
    payment_delays      INTEGER DEFAULT 0,
    avg_payment_days    DECIMAL(5, 2),
    prebooking_count    INTEGER DEFAULT 0,
    disputes_filed      INTEGER DEFAULT 0,
    calculated_score    DECIMAL(5, 2),
    created_at          TIMESTAMP DEFAULT NOW(),
    UNIQUE(customer_id, metric_date)
);

CREATE INDEX idx_customer_metrics_customer ON customer_metrics(customer_id);
CREATE INDEX idx_customer_metrics_date ON customer_metrics(metric_date DESC);

-- Current aggregated scores (fast lookup)
CREATE TABLE driver_scores (
    driver_id       UUID PRIMARY KEY REFERENCES drivers(id) ON DELETE CASCADE,
    current_score   DECIMAL(5, 2) NOT NULL DEFAULT 50.0,
    total_orders    INTEGER DEFAULT 0,
    reliability_pct DECIMAL(5, 2),  -- on-time percentage
    last_updated    TIMESTAMP DEFAULT NOW()
);

CREATE TABLE customer_scores (
    customer_id     UUID PRIMARY KEY REFERENCES customers(id) ON DELETE CASCADE,
    current_score   DECIMAL(5, 2) NOT NULL DEFAULT 50.0,
    total_orders    INTEGER DEFAULT 0,
    payment_reliability_pct DECIMAL(5, 2),
    last_updated    TIMESTAMP DEFAULT NOW()
);


-- ============================================================
-- 13. LIVE TRACKING & FORECASTING
-- ============================================================

CREATE TABLE live_tracking (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    order_id        UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    vehicle_id      UUID NOT NULL REFERENCES vehicles(id),
    latitude        DECIMAL(10, 7) NOT NULL,
    longitude       DECIMAL(10, 7) NOT NULL,
    speed_kmph      DECIMAL(5, 2),
    heading         DECIMAL(5, 2),
    recorded_at     TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_tracking_order ON live_tracking(order_id);
CREATE INDEX idx_tracking_vehicle ON live_tracking(vehicle_id);
CREATE INDEX idx_tracking_time ON live_tracking(recorded_at DESC);

-- Vehicle arrival forecasting (ML model output)
CREATE TABLE vehicle_arrival_forecast (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    order_id        UUID REFERENCES orders(id) ON DELETE CASCADE,
    vehicle_id      UUID REFERENCES vehicles(id),
    eta_minutes     INTEGER,
    confidence      DECIMAL(3, 2),  -- 0.00 to 1.00
    model_version   VARCHAR(20),
    predicted_at    TIMESTAMP DEFAULT NOW(),
    features_used   JSONB  -- for model auditing
);

CREATE INDEX idx_forecast_order ON vehicle_arrival_forecast(order_id);
CREATE INDEX idx_forecast_vehicle ON vehicle_arrival_forecast(vehicle_id);

-- Inventory snapshot (hourly aggregation for ML)
CREATE TABLE vehicle_inventory_snapshot (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    snapshot_time       TIMESTAMP NOT NULL DEFAULT NOW(),
    city_id             UUID NOT NULL REFERENCES cities(id),
    vehicle_class       VARCHAR(10) NOT NULL,
    body_type           VARCHAR(20) NOT NULL,
    total_vehicles      INTEGER DEFAULT 0,
    online_vehicles     INTEGER DEFAULT 0,
    in_shipment         INTEGER DEFAULT 0,
    available_vehicles  INTEGER DEFAULT 0,
    created_at          TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_inventory_city_time ON vehicle_inventory_snapshot(city_id, snapshot_time DESC);
CREATE INDEX idx_inventory_class ON vehicle_inventory_snapshot(vehicle_class, body_type);


-- ============================================================
-- 14. CONSIGNMENTS & CONSIGNEES
-- ============================================================

CREATE TABLE consignees (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name            VARCHAR(200) NOT NULL,
    phone           VARCHAR(15) NOT NULL,
    address         TEXT,
    pincode         VARCHAR(6) NOT NULL,
    city_id         UUID REFERENCES cities(id),
    gst_number      VARCHAR(15),
    is_tobilled     BOOLEAN DEFAULT FALSE,  -- To-pay consignee
    created_at      TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_consignees_city ON consignees(city_id);
CREATE INDEX idx_consignees_pincode ON consignees(pincode);


-- ============================================================
-- 15. AUDIT LOG (Global)
-- ============================================================

CREATE TABLE audit_logs (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    entity_type     VARCHAR(50) NOT NULL,  -- 'order', 'payment', 'driver', 'customer', 'vehicle'
    entity_id       UUID NOT NULL,
    action          VARCHAR(50) NOT NULL,  -- 'created', 'updated', 'cancelled', 'blocked', 'refunded'
    performed_by    UUID REFERENCES users(id),
    performed_by_type VARCHAR(20) CHECK (performed_by_type IN ('admin', 'system', 'customer', 'driver', 'api')),
    old_values      JSONB,
    new_values      JSONB,
    ip_address      INET,
    user_agent      TEXT,
    created_at      TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_audit_entity ON audit_logs(entity_type, entity_id);
CREATE INDEX idx_audit_user ON audit_logs(performed_by);
CREATE INDEX idx_audit_time ON audit_logs(created_at DESC);


-- ============================================================
-- 16. TERMS & CONDITIONS (Versioned)
-- ============================================================

CREATE TABLE terms_conditions (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    party_type      VARCHAR(10) NOT NULL CHECK (party_type IN ('vendor', 'customer', 'driver')),
    version         INTEGER NOT NULL,
    content         TEXT NOT NULL,
    effective_from  DATE NOT NULL DEFAULT CURRENT_DATE,
    created_at      TIMESTAMP DEFAULT NOW(),
    UNIQUE(party_type, version)
);

-- Track acceptance
CREATE TABLE terms_acceptance (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    terms_id        UUID NOT NULL REFERENCES terms_conditions(id),
    user_id         UUID NOT NULL REFERENCES users(id),
    accepted_at     TIMESTAMP DEFAULT NOW(),
    ip_address      INET,
    UNIQUE(terms_id, user_id)
);

CREATE INDEX idx_terms_acceptance_user ON terms_acceptance(user_id);


-- ============================================================
-- 17. NOTIFICATIONS & ALERTS
-- ============================================================

CREATE TABLE notifications (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    recipient_id    UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    recipient_type  VARCHAR(20) NOT NULL CHECK (recipient_type IN ('customer', 'driver', 'vendor', 'admin')),
    channel         VARCHAR(20) NOT NULL CHECK (channel IN ('whatsapp', 'sms', 'email', 'push', 'in_app')),
    title           VARCHAR(200),
    body            TEXT NOT NULL,
    related_entity  VARCHAR(50),  -- 'order', 'payment', etc.
    related_id      UUID,
    status          VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'sent', 'delivered', 'read', 'failed')),
    sent_at         TIMESTAMP,
    created_at      TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_notifications_recipient ON notifications(recipient_id);
CREATE INDEX idx_notifications_status ON notifications(status);
CREATE INDEX idx_notifications_created ON notifications(created_at DESC);


-- ============================================================
-- 18. UPDATED_AT TRIGGER (Auto-update timestamp)
-- ============================================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply to all tables with updated_at
CREATE TRIGGER trg_users_updated BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_customers_updated BEFORE UPDATE ON customers FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_vendors_updated BEFORE UPDATE ON vendors FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_drivers_updated BEFORE UPDATE ON drivers FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_vehicles_updated BEFORE UPDATE ON vehicles FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_orders_updated BEFORE UPDATE ON orders FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_payments_updated BEFORE UPDATE ON payments FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();


-- ============================================================
-- 19. SEED DATA (City Tiers from FreightCalculator.tsx)
-- ============================================================

INSERT INTO cities (name, tier, state, pincode, latitude, longitude) VALUES
('Bengaluru',  'metro',  'Karnataka',    '560001', 12.9716, 77.5946),
('Chennai',    'metro',  'Tamil Nadu',   '600001', 13.0827, 80.2707),
('Coimbatore', 'tier_1', 'Tamil Nadu',   '641001', 11.0168, 76.9558),
('Erode',      'tier_2', 'Tamil Nadu',   '638001', 11.3410, 77.7172),
('Tiruppur',   'tier_2', 'Tamil Nadu',   '641601', 11.1085, 77.3411),
('Salem',      'tier_2', 'Tamil Nadu',   '636001', 11.6643, 78.1460),
('Karur',      'tier_3', 'Tamil Nadu',   '639001', 10.9601, 78.0766),
('Sri City',   'tier_2', 'Andhra Pradesh','517583', 13.6800, 80.0200),
('Namakkal',   'tier_2', 'Tamil Nadu',   '637001', 11.2214, 78.1671),
('Hyderabad',  'tier_1', 'Telangana',    '500001', 17.3850, 78.4867),
('Kochi',      'tier_1', 'Kerala',       '682001', 9.9312,  76.2673),
('Ooty',       'tier_3', 'Tamil Nadu',   '643001', 11.4102, 76.6950);


-- Seed material types
INSERT INTO material_types (name, required_body, is_hazardous, max_weight_tons) VALUES
('Commodity',         'open',    FALSE, 40),
('Electronics',       'closed',  FALSE, 20),
('Heavy Engineering', 'flatbed', FALSE, 45),
('Pharma',            'freezer', FALSE, 15),
('Textiles',          'closed',  FALSE, 25),
('Agriculture',       'open',    FALSE, 30),
('Chemicals',         'tanker',  TRUE,  20);


-- Seed vehicle models
INSERT INTO vehicle_models (brand, model_name, vehicle_class, body_type, tonnage_capacity, fuel_type, mileage_kmpl) VALUES
('Tata',           'Ace',            'LCV', 'open',    1.0,  'diesel', 18.0),
('Tata',           '407',            'LCV', 'open',    2.5,  'diesel', 14.0),
('Mahindra',       'Blazo 17',       'MCV', 'closed',  9.0,  'diesel', 8.0),
('Ashok Leyland',  'Boss 1215',      'MCV', 'open',    7.5,  'diesel', 9.0),
('Eicher',         'Pro 2049',       'MCV', 'closed',  7.0,  'diesel', 10.0),
('Tata',           'Prima 4928',     'HCV', 'open',    25.0, 'diesel', 4.5),
('Volvo',          'FM 440',         'HCV', 'container',35.0,'diesel', 3.5),
('Bharat Benz',    '2823R',          'HCV', 'closed',  28.0, 'diesel', 5.0);


-- Seed base pricing rates
INSERT INTO pricing_base_rates (vehicle_class, origin_tier, destination_tier, base_rate_per_km, min_charge) VALUES
('mini_truck',   'metro',  'metro',   18.0, 400),
('mini_truck',   'metro',  'tier_1',  18.0, 400),
('mini_truck',   'tier_2', 'tier_2',  16.0, 350),
('LCV',          'metro',  'metro',   25.0, 500),
('LCV',          'metro',  'tier_1',  25.0, 500),
('LCV',          'tier_2', 'tier_2',  22.0, 450),
('MCV',          'metro',  'metro',   38.0, 800),
('MCV',          'metro',  'tier_1',  38.0, 800),
('MCV',          'tier_2', 'tier_2',  35.0, 700),
('HCV',          'metro',  'metro',   52.0, 1200),
('HCV',          'metro',  'tier_1',  52.0, 1200),
('HCV',          'tier_2', 'tier_2',  48.0, 1000),
('trailer',      'metro',  'metro',   68.0, 2000),
('trailer',      'metro',  'tier_1',  68.0, 2000);


-- Seed route distances (from FreightCalculator.tsx fallback)
INSERT INTO route_distances (origin_city_id, dest_city_id, distance_km, source)
SELECT o.id, d.id, dist.km, 'manual'
FROM (VALUES
    ('Bengaluru', 'Chennai', 350),
    ('Chennai', 'Bengaluru', 350),
    ('Chennai', 'Coimbatore', 500),
    ('Coimbatore', 'Chennai', 500),
    ('Coimbatore', 'Bengaluru', 360),
    ('Bengaluru', 'Coimbatore', 360),
    ('Erode', 'Bengaluru', 260),
    ('Bengaluru', 'Erode', 260),
    ('Tiruppur', 'Chennai', 450),
    ('Chennai', 'Tiruppur', 450),
    ('Salem', 'Erode', 65),
    ('Erode', 'Salem', 65),
    ('Salem', 'Karur', 95),
    ('Karur', 'Salem', 95),
    ('Salem', 'Bengaluru', 200),
    ('Bengaluru', 'Salem', 200),
    ('Erode', 'Chennai', 400),
    ('Chennai', 'Erode', 400),
    ('Chennai', 'Sri City', 75),
    ('Sri City', 'Chennai', 75),
    ('Chennai', 'Namakkal', 350),
    ('Namakkal', 'Chennai', 350),
    ('Sri City', 'Bengaluru', 350),
    ('Bengaluru', 'Sri City', 350),
    ('Erode', 'Tiruppur', 55),
    ('Tiruppur', 'Erode', 55)
) AS dist(origin_name, dest_name, km)
JOIN cities o ON o.name = dist.origin_name
JOIN cities d ON d.name = dist.dest_name;


-- ============================================================
-- SCHEMA COMPLETE
-- Total: 25 tables, 80+ indexes, full FK relationships
-- ============================================================
